// TOKENS
int ::= ? [0-9_]+ ? | ? 0x[0-9A-z_]+ ? | ? 0b[0-1_]+ ? | ? 0o[0-7_]+ ?
char ::= "'" ? . ?
string ::= '"' ? .+ ? '"'
literal ::= <int> | <char> | <string>
identifier ::= ? \S+ ?
comment ::= ? #.+$ ?


// INTERMEDIATE RULES
program ::= <statement>+

statement ::= <def> | <decl>
expression ::= (
		<literal> |
		<while> |
		<block> |
		<if> |
		<intrinsic> |
		<identifier>
	)


// MISC
effect ::= '(' <identifier>* [ '->' <identifier>* ] ')'  // ( x y -> z )


// STATEMENTS
// def neg { { 1 2 - } * }
def ::= 'def' <identifier> <expression>

// decl foo (int int -> int)
decl ::= 'decl' <identifier> <effect>


// EXPRESSIONS
// if =1 { "true" print } { "false" print }
if ::= 'if' <expression> <expression> [ 'else' <expression> ]

// while { dup 10 < }
//   ++
while ::= 'while' <expression> <expression>

// { foo bar }
block ::= '{' <expression>+ '}'


// INSTRINSICS
ops ::= (
		'add' | 'sub' | 'mul' | 'div' | 'mod' | 'lsh' | 'rsh' |
		'lt' | 'gt' | 'eq' |
		'and' | 'or' | 'not' | 'xor' |
		'band' | 'bor' | 'bnot' | 'bxor' |
		'word'
	)

// at @3
intrinsic ::= <ops> | <arg_intrinsic>
arg_intrinsic ::= ( 'cp' | 'mv' | 'rm' ) <literal>

